import React from "react";

const sizeClasses = {
  txtSourceSansProSemiBold36WhiteA700: "font-semibold font-sourcesanspro",
  txtRobotoRomanSemiBold26Red30001: "font-roboto font-semibold",
  txtVolkhovBold22: "font-bold font-volkhov",
  txtVolkhovBold20: "font-bold font-volkhov",
  txtNotoSansHebrewDroidRegular32: "font-normal font-notosanshebrewdroid",
  txtMulishRegular18: "font-mulish font-normal",
  txtRubikMedium31: "font-medium font-rubik",
  txtNotoTraditionalNushuRegular32: "font-normal font-nototraditionalnushu",
  txtMulishSemiBold13: "font-mulish font-semibold",
  txtMulishSemiBold12: "font-mulish font-semibold",
  txtMulishRegular15: "font-mulish font-normal",
  txtMulishRegular14: "font-mulish font-normal",
  txtRubikMedium36: "font-medium font-rubik",
  txtInterRegular25: "font-inter font-normal",
  txtInterRegular16Black90066: "font-inter font-normal",
  txtMulishSemiBold14Gray600: "font-mulish font-semibold",
  txtMulishSemiBold16: "font-mulish font-semibold",
  txtMulishSemiBold15: "font-mulish font-semibold",
  txtMulishSemiBold14: "font-mulish font-semibold",
  txtMulishSemiBold16Gray600: "font-mulish font-semibold",
  txtLatoBold20: "font-bold font-lato",
  txtNunitoRegular12: "font-normal font-nunito",
  txtOpenSansRomanSemiBold32: "font-opensans font-semibold",
  txtNunitoRegular14: "font-normal font-nunito",
  txtNunitoRegular15: "font-normal font-nunito",
  txtOpenSansRegular16: "font-normal font-opensans",
  txtPoppinsRegular14: "font-normal font-poppins",
  txtLatoSemiBold16: "font-lato font-semibold",
  txtLatoRegular20: "font-lato font-normal",
  txtSourceSansProSemiBold20: "font-semibold font-sourcesanspro",
  txtSourceSansProSemiBold27: "font-semibold font-sourcesanspro",
  txtVolkhovBold17: "font-bold font-volkhov",
  txtInterMedium17Black900cc: "font-inter font-medium",
  txtSFProDisplayMedium17Bluegray90003: "font-medium font-sfprodisplay",
  txtVolkhovBold15: "font-bold font-volkhov",
  txtMulishBold14Gray600: "font-bold font-mulish",
  txtMulishBold15Bluegray900: "font-bold font-mulish",
  txtNunitoRegular12RedA400: "font-normal font-nunito",
  txtInterRegular14: "font-inter font-normal",
  txtInterRegular16: "font-inter font-normal",
  txtRubikMedium16WhiteA700: "font-medium font-rubik",
  txtMulishSemiBold14WhiteA700: "font-mulish font-semibold",
  txtSFProDisplayMedium15: "font-medium font-sfprodisplay",
  txtSFProDisplayMedium16: "font-medium font-sfprodisplay",
  txtSFProDisplayMedium17: "font-medium font-sfprodisplay",
  txtSFProDisplayMedium18: "font-medium font-sfprodisplay",
  txtMulishRomanExtraBold15Bluegray700: "font-extrabold font-mulish",
  txtSFProDisplayRegular18: "font-normal font-sfprodisplay",
  txtSFProDisplayRegular18Gray90001: "font-normal font-sfprodisplay",
  txtSFProDisplayRegular16: "font-normal font-sfprodisplay",
  txtMulishExtraBold11: "font-extrabold font-mulish",
  txtOpenSansRomanSemiBold20: "font-opensans font-semibold",
  txtMulishExtraBold15: "font-extrabold font-mulish",
  txtMulishExtraBold14: "font-extrabold font-mulish",
  txtOpenSansRomanSemiBold24: "font-opensans font-semibold",
  txtDarkerGrotesqueSemiBold14Bluegray90010:
    "font-darkergrotesque font-semibold",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtMulishBold15Bluegray90004: "font-bold font-mulish",
  txtMulishExtraBold16: "font-extrabold font-mulish",
  txtMulishBold14Teal200: "font-bold font-mulish",
  txtVolkhovBold48: "font-bold font-volkhov",
  txtSFProDisplayMedium16Gray9007f: "font-medium font-sfprodisplay",
  txtRobotoRomanSemiBold45: "font-roboto font-semibold",
  txtRobotoRomanRegular24: "font-normal font-roboto",
  txtInterMedium12Gray60001: "font-inter font-medium",
  txtOpenSansRomanSemiBold16: "font-opensans font-semibold",
  txtVolkhovBold20Pink700: "font-bold font-volkhov",
  txtVolkhovBold36: "font-bold font-volkhov",
  txtInterBold36: "font-bold font-inter",
  txtPoppinsRegular14Bluegray90009: "font-normal font-poppins",
  txtMulishSemiBold15Gray600: "font-mulish font-semibold",
  txtOpenSansRomanSemiBold16Black900e2: "font-opensans font-semibold",
  txtInterBold32: "font-bold font-inter",
  txtOpenSansRomanSemiBold14: "font-opensans font-semibold",
  txtMulishSemiBold16WhiteA700: "font-mulish font-semibold",
  txtOpenSansSemiBold1308: "font-opensans font-semibold",
  txtVolkhovBold15Bluegray900: "font-bold font-volkhov",
  txtMulishBlack30: "font-black font-mulish",
  txtDarkerGrotesqueSemiBold24: "font-darkergrotesque font-semibold",
  txtInterRegular14Indigo600: "font-inter font-normal",
  txtPoppinsMedium14Gray500: "font-medium font-poppins",
  txtMulishRomanSemiBold15: "font-mulish font-semibold",
  txtSourceSansProSemiBold1744WhiteA700: "font-semibold font-sourcesanspro",
  txtMulishRomanSemiBold18: "font-mulish font-semibold",
  txtMulishSemiBold15Bluegray700: "font-mulish font-semibold",
  txtVolkhovBold36WhiteA700: "font-bold font-volkhov",
  txtInterMedium17Bluegray90003: "font-inter font-medium",
  txtMulishBold20: "font-bold font-mulish",
  txtVolkhovBold64: "font-bold font-volkhov",
  txtMulishBold22: "font-bold font-mulish",
  txtPoppinsBold36: "font-bold font-poppins",
  txtOpenSansRomanBold16: "font-bold font-opensans",
  txtMulishRomanBold14: "font-bold font-mulish",
  txtOpenSansRomanSemiBold20Black900e2: "font-opensans font-semibold",
  txtVolkhovBold20Teal200: "font-bold font-volkhov",
  txtMulishBlack48: "font-black font-mulish",
  txtSourceSansProSemiBold1744: "font-semibold font-sourcesanspro",
  txtRobotoRomanSemiBold26: "font-roboto font-semibold",
  txtMulishSemiBold14Bluegray70004: "font-mulish font-semibold",
  txtRobotoRomanSemiBold24: "font-roboto font-semibold",
  txtNicoMojiRegular26: "font-nicomoji font-normal",
  txtManropeBold8: "font-bold font-manrope",
  txtDarkerGrotesqueSemiBold13: "font-darkergrotesque font-semibold",
  txtRobotoRomanSemiBold20: "font-roboto font-semibold",
  txtDarkerGrotesqueSemiBold14: "font-darkergrotesque font-semibold",
  txtRobotoRomanMedium24: "font-medium font-roboto",
  txtSourceSerifProSemiBold36: "font-semibold font-sourceserifpro",
  txtMulishSemiBoldItalic14: "font-mulish font-semibold italic",
  txtSFProDisplayMedium28: "font-medium font-sfprodisplay",
  txtRobotoRomanMedium20: "font-medium font-roboto",
  txtInterBold14: "font-bold font-inter",
  txtInterMedium12: "font-inter font-medium",
  txtDarkerGrotesqueBold20: "font-bold font-darkergrotesque",
  txtMulishBold14Bluegray700: "font-bold font-mulish",
  txtInterMedium17: "font-inter font-medium",
  txtNunitoRegular14Bluegray300: "font-normal font-nunito",
  txtMulishSemiBold15Gray900: "font-mulish font-semibold",
  txtMulishRegular15Bluegray700: "font-mulish font-normal",
  txtInterBold12: "font-bold font-inter",
  txtMulishBold13: "font-bold font-mulish",
  txtNicoMojiRegular26Gray900: "font-nicomoji font-normal",
  txtMulishBold15: "font-bold font-mulish",
  txtNotoTraditionalNushuRegular32Black900:
    "font-normal font-nototraditionalnushu",
  txtMulishBold14: "font-bold font-mulish",
  txtMulishBold16: "font-bold font-mulish",
  txtSFProDisplayMedium15Gray9007f: "font-medium font-sfprodisplay",
  txtInterMedium20: "font-inter font-medium",
  txtMulishBold18: "font-bold font-mulish",
  txtDarkerGrotesqueSemiBold14Green900: "font-darkergrotesque font-semibold",
  txtNotoTraditionalNushuRegular32Gray90002:
    "font-normal font-nototraditionalnushu",
  txtSFProDisplayMedium20: "font-medium font-sfprodisplay",
  txtSFProDisplayMedium22: "font-medium font-sfprodisplay",
  txtRobotoRomanSemiBold32: "font-roboto font-semibold",
  txtRobotoRomanMedium16: "font-medium font-roboto",
  txtRobotoRomanRegular14: "font-normal font-roboto",
  txtLatoExtraBold22: "font-extrabold font-lato",
  txtVolkhovBold20Red600: "font-bold font-volkhov",
  txtVolkhovBold20Black900: "font-bold font-volkhov",
  txtOpenSansRomanSemiBold24Black900d3: "font-opensans font-semibold",
  txtLatoBold30: "font-bold font-lato",
  txtManropeSemiBold16: "font-manrope font-semibold",
  txtRubikRegular24: "font-normal font-rubik",
  txtPoppinsMedium13: "font-medium font-poppins",
  txtOpenSansSemiBold16: "font-opensans font-semibold",
  txtSFProDisplayMedium17Purple300: "font-medium font-sfprodisplay",
  txtPoppinsMedium14: "font-medium font-poppins",
  txtOpenSansSemiBold15: "font-opensans font-semibold",
  txtSFProDisplayMedium17Bluegray90099: "font-medium font-sfprodisplay",
  txtSourceSansProSemiBold36: "font-semibold font-sourcesanspro",
  txtRubikMedium16: "font-medium font-rubik",
  txtNotoSansHebrewDroidRegular32Red600: "font-normal font-notosanshebrewdroid",
  txtVolkhovRegular16: "font-normal font-volkhov",
  txtVolkhovRegular18: "font-normal font-volkhov",
  txtInterMedium17Purple300: "font-inter font-medium",
  txtSourceSansProBold24: "font-bold font-sourcesanspro",
  txtMulishLight23: "font-light font-mulish",
  txtPoppinsRegular36: "font-normal font-poppins",
  txtMulishRomanExtraBold15: "font-extrabold font-mulish",
  txtRobotoRomanSemiBold26RedA200: "font-roboto font-semibold",
  txtManropeMedium10: "font-manrope font-medium",
  txtMulishRomanSemiBold15Gray900: "font-mulish font-semibold",
  txtPoppinsRegular40: "font-normal font-poppins",
  txtInterSemiBold20: "font-inter font-semibold",
  txtMulishRomanExtraBold15Gray900: "font-extrabold font-mulish",
  txtRubikMedium27: "font-medium font-rubik",
  txtInterMedium12WhiteA700cc: "font-inter font-medium",
  txtSourceSansProBold36: "font-bold font-sourcesanspro",
  txtNicoMojiRegular26Bluegray700: "font-nicomoji font-normal",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
