import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Homepage</Link>
        </li>
        <li>
          <Link to="/editprofile">Editprofile</Link>
        </li>
        <li>
          <Link to="/updatesuccessful">Updatesuccessful</Link>
        </li>
        <li>
          <Link to="/signupone">SignUpOne</Link>
        </li>
        <li>
          <Link to="/signuptwo">SignUpTwo</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/forgotpasswordstepone">ForgotPasswordStepOne</Link>
        </li>
        <li>
          <Link to="/forgotpasswordsteptwo">ForgotPasswordStepTwo</Link>
        </li>
        <li>
          <Link to="/resetpasswordstepone">ResetPasswordStepOne</Link>
        </li>
        <li>
          <Link to="/resetpasswordsteptwo">ResetPasswordStepTwo</Link>
        </li>
        <li>
          <Link to="/listtimesharebooking">ListTimeshareBooking</Link>
        </li>
        <li>
          <Link to="/timesharebookingdetail">TimeshareBookingDetail</Link>
        </li>
        <li>
          <Link to="/exchangeone">ExchangeOne</Link>
        </li>
        <li>
          <Link to="/exchange2exchangelist">Exchange2ExchangeList</Link>
        </li>
        <li>
          <Link to="/exchange3detail">Exchange3Detail</Link>
        </li>
        <li>
          <Link to="/exchange4myunit">Exchange4MyUnit</Link>
        </li>
        <li>
          <Link to="/exchange5exchanging">Exchange5Exchanging</Link>
        </li>
        <li>
          <Link to="/exchange6confirm">Exchange6Confirm</Link>
        </li>
        <li>
          <Link to="/exchange7success">Exchange7Success</Link>
        </li>
        <li>
          <Link to="/exchane8view">Exchane8View</Link>
        </li>
        <li>
          <Link to="/memberprofile">MemberProfile</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/mytimeshare">MyTimeshare</Link>
        </li>
        <li>
          <Link to="/createtimesharethree">CreateTimeshareThree</Link>
        </li>
        <li>
          <Link to="/createtimesharetwo">CreateTimeshareTwo</Link>
        </li>
        <li>
          <Link to="/createtimeshareone">CreateTimeshareOne</Link>
        </li>
        <li>
          <Link to="/createtimeshare">CreateTimeshare</Link>
        </li>
        <li>
          <Link to="/requestlist">RequestList</Link>
        </li>
        <li>
          <Link to="/requestlistdetail">RequestListDetail</Link>
        </li>
        <li>
          <Link to="/acceptrequest">AcceptRequest</Link>
        </li>
        <li>
          <Link to="/requestacceptview">RequestAcceptView</Link>
        </li>
        <li>
          <Link to="/waitlistexchangerequestsone">
            WaitlistExchangeRequestsOne
          </Link>
        </li>
        <li>
          <Link to="/waitlistexchangerequests">WaitlistExchangeRequests</Link>
        </li>
        <li>
          <Link to="/walletone">WalletOne</Link>
        </li>
        <li>
          <Link to="/wallet">Wallet</Link>
        </li>
        <li>
          <Link to="/waitlistexchangerequeststwo">
            WaitlistExchangeRequestsTwo
          </Link>
        </li>
        <li>
          <Link to="/bookingfive">BookingFive</Link>
        </li>
        <li>
          <Link to="/bookingone">BookingOne</Link>
        </li>
        <li>
          <Link to="/bookingtwo">BookingTwo</Link>
        </li>
        <li>
          <Link to="/booking21">Booking21</Link>
        </li>
        <li>
          <Link to="/bookingthree">BookingThree</Link>
        </li>
        <li>
          <Link to="/bookingfour">BookingFour</Link>
        </li>
        <li>
          <Link to="/cancelbooking">CancelBooking</Link>
        </li>
        <li>
          <Link to="/cancellationandrefundprocess">
            Cancellationandrefundprocess
          </Link>
        </li>
        <li>
          <Link to="/cancellationandrefundprocesstwo">
            CancellationandrefundprocessTwo
          </Link>
        </li>
        <li>
          <Link to="/rentexchangeone">RentExchangeOne</Link>
        </li>
        <li>
          <Link to="/cancellationandrefundprocessone">
            CancellationandrefundprocessOne
          </Link>
        </li>
        <li>
          <Link to="/rentexchangetwo">RentExchangeTwo</Link>
        </li>
        <li>
          <Link to="/rentexchange">RentExchange</Link>
        </li>
        <li>
          <Link to="/cancelexchange">CancelExchange</Link>
        </li>
        <li>
          <Link to="/rentexchangeseven">RentExchangeSeven</Link>
        </li>
        <li>
          <Link to="/rentexchangesix">RentExchangeSix</Link>
        </li>
        <li>
          <Link to="/rentexchangeeight">RentExchangeEight</Link>
        </li>
        <li>
          <Link to="/rentexchangefive">RentExchangeFive</Link>
        </li>
        <li>
          <Link to="/cancelexchangeone">CancelExchangeOne</Link>
        </li>
        <li>
          <Link to="/rentexchangefour">RentExchangeFour</Link>
        </li>
        <li>
          <Link to="/rentexchangethree">RentExchangeThree</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
